%RUN_01_TIA_BASELINE Generate the TIA v0.1 behavioural baseline.
%
% This script creates CSV source data before plotting, extracts baseline
% metrics, generates magnitude and phase figures, and writes a figure
% manifest. It does not run SPICE, hardware measurement, or noise analysis.

scriptDir = fileparts(mfilename('fullpath'));
tiaRoot = fileparts(scriptDir);
functionsDir = fullfile(tiaRoot, 'functions');
resultsDir = fullfile(tiaRoot, 'results');
figuresDir = fullfile(tiaRoot, 'figures');

addpath(functionsDir);

if ~exist(resultsDir, 'dir')
    mkdir(resultsDir);
end

if ~exist(figuresDir, 'dir')
    mkdir(figuresDir);
end

params = struct();
params.Rf = 100e3;
params.Cf = 1e-12;
params.Cpd = 2e-12;
params.A0 = 1e5;
params.ft_Hz = 100e6;
params.f_Hz = logspace(1, 8, 2000).';

response = tia_response( ...
    params.f_Hz, params.Rf, params.Cf, params.Cpd, ...
    params.A0, params.ft_Hz);

metrics = extract_tia_metrics( ...
    response.f_Hz, response.Zt_nonideal, ...
    params.Rf, response.fc_ideal_Hz);

classification = classify_tia_design_region(metrics);

responseTable = table( ...
    response.f_Hz, ...
    abs(response.Zt_ideal), ...
    unwrap(angle(response.Zt_ideal))*180/pi, ...
    abs(response.Zt_nonideal), ...
    unwrap(angle(response.Zt_nonideal))*180/pi, ...
    abs(response.G_nonideal), ...
    unwrap(angle(response.G_nonideal))*180/pi, ...
    'VariableNames', { ...
        'f_Hz', ...
        'mag_Zt_ideal_ohm', ...
        'phase_Zt_ideal_deg', ...
        'mag_Zt_nonideal_ohm', ...
        'phase_Zt_nonideal_deg', ...
        'mag_G_nonideal_ohm', ...
        'phase_G_nonideal_deg'});

responseCsv = fullfile(resultsDir, 'tia_baseline_response.csv');
writetable(responseTable, responseCsv);

metricsTable = table( ...
    params.Rf, ...
    params.Cf, ...
    params.Cpd, ...
    params.A0, ...
    params.ft_Hz, ...
    response.fp_Hz, ...
    response.fc_ideal_Hz, ...
    response.capacitive_noise_gain, ...
    response.gbw_margin_index, ...
    metrics.Rf_eff_ohm, ...
    metrics.gain_error_pct, ...
    metrics.bandwidth_Hz, ...
    metrics.bandwidth_ratio, ...
    metrics.peaking_dB, ...
    metrics.peaking_frequency_Hz, ...
    metrics.phase_at_bandwidth_deg, ...
    string(classification.region_label), ...
    classification.region_code, ...
    'VariableNames', { ...
        'Rf_ohm', ...
        'Cf_F', ...
        'Cpd_F', ...
        'A0', ...
        'ft_Hz', ...
        'fp_Hz', ...
        'fc_ideal_Hz', ...
        'capacitive_noise_gain', ...
        'gbw_margin_index', ...
        'Rf_eff_ohm', ...
        'gain_error_pct', ...
        'bandwidth_Hz', ...
        'bandwidth_ratio', ...
        'peaking_dB', ...
        'peaking_frequency_Hz', ...
        'phase_at_bandwidth_deg', ...
        'classification', ...
        'classification_code'});

metricsCsv = fullfile(resultsDir, 'baseline_metrics.csv');
writetable(metricsTable, metricsCsv);

keyParameters = sprintf( ...
    'Rf=%.3g ohm; Cf=%.3g F; Cpd=%.3g F; A0=%.3g; ft=%.3g Hz', ...
    params.Rf, params.Cf, params.Cpd, params.A0, params.ft_Hz);

magFig = figure('Color', 'w', 'Name', 'TIA baseline magnitude');
semilogx(response.f_Hz, 20*log10(abs(response.Zt_ideal)), ...
    'LineWidth', 1.5, 'DisplayName', 'Ideal op-amp');
hold on;
semilogx(response.f_Hz, 20*log10(abs(response.Zt_nonideal)), ...
    'LineWidth', 1.5, 'DisplayName', 'Finite A0 and ft');
grid on;
box on;
xlabel('Frequency (Hz)');
ylabel('Transimpedance magnitude (dB ohm)');
title('TIA baseline magnitude response');
legend('Location', 'southwest');
styleBaselineAxes(gca);
formatsMagnitude = exportFigureSet( ...
    magFig, fullfile(figuresDir, 'tia_baseline_magnitude'));
close(magFig);

phaseFig = figure('Color', 'w', 'Name', 'TIA baseline phase');
semilogx(response.f_Hz, unwrap(angle(response.G_ideal))*180/pi, ...
    'LineWidth', 1.5, 'DisplayName', 'Ideal op-amp');
hold on;
semilogx(response.f_Hz, unwrap(angle(response.G_nonideal))*180/pi, ...
    'LineWidth', 1.5, 'DisplayName', 'Finite A0 and ft');
grid on;
box on;
xlabel('Frequency (Hz)');
ylabel('Inversion-removed phase (deg)');
title('TIA baseline phase response');
legend('Location', 'southwest');
styleBaselineAxes(gca);
formatsPhase = exportFigureSet( ...
    phaseFig, fullfile(figuresDir, 'tia_baseline_phase'));
close(phaseFig);

figureManifest = table( ...
    ["tia_baseline_magnitude.png"; "tia_baseline_phase.png"], ...
    ["tia_extension/scripts/run_01_tia_baseline.m"; ...
     "tia_extension/scripts/run_01_tia_baseline.m"], ...
    ["tia_extension/results/tia_baseline_response.csv"; ...
     "tia_extension/results/tia_baseline_response.csv"], ...
    [string(keyParameters); string(keyParameters)], ...
    [ ...
        "Baseline MATLAB behavioural TIA magnitude response comparing ideal and finite-gain op-amp cases."; ...
        "Baseline MATLAB behavioural TIA inversion-removed phase response comparing ideal and finite-gain op-amp cases." ...
    ], ...
    ["clean MATLAB behavioural simulation"; ...
     "clean MATLAB behavioural simulation"], ...
    [string(strjoin(formatsMagnitude, ';')); ...
     string(strjoin(formatsPhase, ';'))], ...
    'VariableNames', { ...
        'figure_filename', ...
        'source_script', ...
        'source_data', ...
        'key_parameters', ...
        'caption', ...
        'data_type', ...
        'export_formats'});

manifestCsv = fullfile(figuresDir, 'figure_manifest_tia.csv');
writetable(figureManifest, manifestCsv);

fprintf('TIA baseline complete.\n');
fprintf('Response data: %s\n', responseCsv);
fprintf('Metrics: %s\n', metricsCsv);
fprintf('Figure manifest: %s\n', manifestCsv);

function styleBaselineAxes(ax)
set(ax, 'FontName', 'Arial', 'FontSize', 11, 'LineWidth', 1);

try
    disableDefaultInteractivity(ax);
catch
end

try
    axtoolbar(ax, {});
catch
end
end

function formats = exportFigureSet(figHandle, basePath)
formats = {};

try
    exportgraphics(figHandle, [basePath '.pdf'], 'ContentType', 'vector');
    formats{end+1} = 'pdf'; %#ok<AGROW>
catch
    try
        print(figHandle, [basePath '.pdf'], '-dpdf', '-bestfit');
        formats{end+1} = 'pdf'; %#ok<AGROW>
    catch
    end
end

try
    exportgraphics(figHandle, [basePath '.svg'], 'ContentType', 'vector');
    formats{end+1} = 'svg'; %#ok<AGROW>
catch
    try
        print(figHandle, [basePath '.svg'], '-dsvg');
        formats{end+1} = 'svg'; %#ok<AGROW>
    catch
    end
end

try
    exportgraphics(figHandle, [basePath '.png'], 'Resolution', 600);
    formats{end+1} = 'png'; %#ok<AGROW>
catch
    print(figHandle, [basePath '.png'], '-dpng', '-r600');
    formats{end+1} = 'png'; %#ok<AGROW>
end
end
