%% Round 7 vendor op-amp datasheet candidate table
% Builds the publication-facing candidate table from the curated datasheet
% source CSV. This script does not import or generate SPICE data.

clear;
clc;

scriptDir = fileparts(mfilename('fullpath'));
tiaRoot = fileparts(scriptDir);
datasheetDir = fullfile(tiaRoot, 'datasheets');

sourceCsv = fullfile(datasheetDir, 'vendor_opamp_datasheet_sources.csv');
candidateCsv = fullfile(datasheetDir, 'vendor_opamp_candidate_table.csv');
candidateSiCsv = fullfile(datasheetDir, 'vendor_opamp_candidate_table_si.csv');
candidateMarkdown = fullfile(datasheetDir, 'vendor_opamp_candidate_table.md');
manifestCsv = fullfile(datasheetDir, 'vendor_opamp_table_manifest.csv');

if ~isfolder(datasheetDir)
    mkdir(datasheetDir);
end

opts = detectImportOptions(sourceCsv, 'TextType', 'string');
opts = setvartype(opts, {'candidate_rank'}, 'double');
sourceTable = readtable(sourceCsv, opts);
sourceTable = sortrows(sourceTable, 'candidate_rank');

candidateTable = sourceTable(:, { ...
    'candidate_rank', ...
    'vendor', ...
    'part_number', ...
    'lifecycle_status', ...
    'input_type', ...
    'tia_candidate_role', ...
    'voltage_noise_nV_per_sqrtHz', ...
    'voltage_noise_condition', ...
    'current_noise_fA_per_sqrtHz', ...
    'current_noise_condition', ...
    'ft_proxy_MHz', ...
    'ft_proxy_metric', ...
    'min_stable_gain_V_per_V', ...
    'input_capacitance_total_pF', ...
    'supply_min_V', ...
    'supply_max_V', ...
    'package_notes', ...
    'spice_model_status', ...
    'candidate_notes', ...
    'primary_source_url' ...
    });

writetable(candidateTable, candidateCsv);

siTable = table();
siTable.candidate_rank = sourceTable.candidate_rank;
siTable.vendor = sourceTable.vendor;
siTable.part_number = sourceTable.part_number;
siTable.input_type = sourceTable.input_type;
siTable.tia_candidate_role = sourceTable.tia_candidate_role;
siTable.voltage_noise_V_per_sqrtHz = sourceTable.voltage_noise_nV_per_sqrtHz .* 1e-9;
siTable.voltage_noise_condition = sourceTable.voltage_noise_condition;
siTable.current_noise_A_per_sqrtHz = sourceTable.current_noise_fA_per_sqrtHz .* 1e-15;
siTable.current_noise_condition = sourceTable.current_noise_condition;
siTable.ft_proxy_Hz = sourceTable.ft_proxy_MHz .* 1e6;
siTable.ft_proxy_metric = sourceTable.ft_proxy_metric;
siTable.min_stable_gain_V_per_V = sourceTable.min_stable_gain_V_per_V;
siTable.input_capacitance_total_F = sourceTable.input_capacitance_total_pF .* 1e-12;
siTable.input_capacitance_common_mode_F = sourceTable.input_capacitance_common_mode_pF .* 1e-12;
siTable.input_capacitance_differential_F = sourceTable.input_capacitance_differential_pF .* 1e-12;
siTable.supply_min_V = sourceTable.supply_min_V;
siTable.supply_max_V = sourceTable.supply_max_V;
siTable.spice_model_status = sourceTable.spice_model_status;
siTable.primary_source_url = sourceTable.primary_source_url;
siTable.source_document = sourceTable.source_document;
siTable.source_accessed_date = sourceTable.source_accessed_date;
siTable.candidate_notes = sourceTable.candidate_notes;
siTable.missing_value_notes = buildMissingValueNotes(sourceTable);

writetable(siTable, candidateSiCsv);

fid = fopen(candidateMarkdown, 'w');
cleanupObj = onCleanup(@() fclose(fid));

fprintf(fid, '# Vendor Op-Amp Datasheet Candidate Table\n\n');
fprintf(fid, 'Round 7 datasheet baseline generated by `tia_extension/scripts/run_09_vendor_opamp_datasheet_table.m` from `tia_extension/datasheets/vendor_opamp_datasheet_sources.csv`.\n\n');
fprintf(fid, 'A machine-readable SI-normalized companion is generated at `tia_extension/datasheets/vendor_opamp_candidate_table_si.csv`.\n\n');
fprintf(fid, 'This table is a candidate-screening aid for later real vendor SPICE macromodel work. It is not SPICE validation, not hardware validation, and not a final op-amp selection rule.\n\n');
fprintf(fid, '| Rank | Vendor | Part | Status | Input | TIA role | e_n (nV/sqrtHz) | i_n (fA/sqrtHz) | ft proxy (MHz) | Min stable gain | C_in total (pF) | Supply (V total) | Packages / model notes |\n');
fprintf(fid, '|---:|---|---|---|---|---|---:|---:|---:|---:|---:|---|---|\n');

for ii = 1:height(candidateTable)
    row = candidateTable(ii, :);
    fprintf(fid, '| %d | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s to %s | %s; %s |\n', ...
        row.candidate_rank, ...
        md(row.vendor), ...
        md(row.part_number), ...
        md(row.lifecycle_status), ...
        md(row.input_type), ...
        md(row.tia_candidate_role), ...
        fmtNum(row.voltage_noise_nV_per_sqrtHz), ...
        fmtNum(row.current_noise_fA_per_sqrtHz), ...
        fmtNum(row.ft_proxy_MHz), ...
        fmtNum(row.min_stable_gain_V_per_V), ...
        fmtNum(row.input_capacitance_total_pF), ...
        fmtNum(row.supply_min_V), ...
        fmtNum(row.supply_max_V), ...
        md(row.package_notes), ...
        md(row.spice_model_status));
end

fprintf(fid, '\n## Source Notes\n\n');
fprintf(fid, '- `ft_proxy_MHz` is a screening parameter for the simplified finite-GBW MATLAB model. For decompensated parts it is the datasheet GBWP and must not be interpreted as unity-gain-stable bandwidth.\n');
fprintf(fid, '- Empty or `NaN` values mean the reviewed datasheet/product summary did not provide a scalar value suitable for this table; they should be confirmed before quantitative ranking.\n');
fprintf(fid, '- Current-noise and input-capacitance values are copied as datasheet screening data and have not been fitted to the MATLAB behavioural model.\n');
fprintf(fid, '- SPICE model availability is recorded only as a planning note. No new vendor macromodel data was imported or compared in Round 7.\n');

clear cleanupObj;

manifest = table( ...
    ["vendor_opamp_candidate_table.csv"; "vendor_opamp_candidate_table_si.csv"], ...
    ["tia_extension/scripts/run_09_vendor_opamp_datasheet_table.m"; "tia_extension/scripts/run_09_vendor_opamp_datasheet_table.m"], ...
    ["tia_extension/datasheets/vendor_opamp_datasheet_sources.csv"; "tia_extension/datasheets/vendor_opamp_datasheet_sources.csv"], ...
    ["tia_extension/datasheets/vendor_opamp_datasheet_parameter_record.md"; "tia_extension/datasheets/vendor_opamp_datasheet_parameter_record.md"], ...
    ["Round 7 vendor op-amp datasheet candidate table in datasheet units for later TIA SPICE macromodel planning."; ...
     "Round 7 vendor op-amp datasheet candidate table normalized to SI units for machine-readable analysis."], ...
    ["datasheet-derived screening table; no SPICE simulation data"; ...
     "SI-normalized datasheet-derived screening table; no SPICE simulation data"], ...
    ["csv;md"; "csv"], ...
    'VariableNames', {'table_file', 'source_script', 'source_data', 'parameter_record', 'caption', 'data_type', 'export_formats'});
writetable(manifest, manifestCsv);

fprintf('Wrote %s\n', candidateCsv);
fprintf('Wrote %s\n', candidateSiCsv);
fprintf('Wrote %s\n', candidateMarkdown);
fprintf('Wrote %s\n', manifestCsv);

function out = fmtNum(value)
    if ismissing(value) || (isnumeric(value) && isnan(value))
        out = "not tabulated";
        return;
    end
    out = string(sprintf('%g', value));
end

function out = md(value)
    out = string(value);
    out = replace(out, '|', '\|');
    out = replace(out, newline, ' ');
end

function notes = buildMissingValueNotes(sourceTable)
    notes = strings(height(sourceTable), 1);
    for ii = 1:height(sourceTable)
        rowNotes = strings(0, 1);
        if isnan(sourceTable.voltage_noise_nV_per_sqrtHz(ii))
            rowNotes(end + 1) = "voltage_noise_V_per_sqrtHz is NaN because no scalar voltage-noise value was available in the reviewed source";
        end
        if isnan(sourceTable.current_noise_fA_per_sqrtHz(ii))
            rowNotes(end + 1) = "current_noise_A_per_sqrtHz is NaN because no scalar current-noise value was available in the reviewed source";
        end
        if isnan(sourceTable.ft_proxy_MHz(ii))
            rowNotes(end + 1) = "ft_proxy_Hz is NaN because no scalar bandwidth or GBWP proxy was available in the reviewed source";
        end
        if isnan(sourceTable.input_capacitance_total_pF(ii))
            rowNotes(end + 1) = "input_capacitance_total_F is NaN because no scalar total input capacitance was available in the reviewed source";
        end
        if isnan(sourceTable.input_capacitance_common_mode_pF(ii))
            rowNotes(end + 1) = "input_capacitance_common_mode_F is NaN because no scalar common-mode input capacitance was available in the reviewed source";
        end
        if isnan(sourceTable.input_capacitance_differential_pF(ii))
            rowNotes(end + 1) = "input_capacitance_differential_F is NaN because no scalar differential input capacitance was available in the reviewed source";
        end
        if isempty(rowNotes)
            notes(ii) = "none";
        else
            notes(ii) = strjoin(rowNotes, "; ");
        end
    end
end
