%RUN_08_NOISE_BANDWIDTH_TRADEOFF Sweep Cf for noise-bandwidth trade-off.
%
% This script saves CSV source data before plotting. It estimates a
% first-pass MATLAB behavioural noise and bandwidth trade-off only; it does
% not run SPICE, hardware measurement, or experimental noise validation.

scriptDir = fileparts(mfilename('fullpath'));
tiaRoot = fileparts(scriptDir);
functionsDir = fullfile(tiaRoot, 'functions');
resultsDir = fullfile(tiaRoot, 'results');
figuresDir = fullfile(tiaRoot, 'figures');

addpath(functionsDir);
ensureDir(resultsDir);
ensureDir(figuresDir);

runId = char(datetime('now', 'TimeZone', 'UTC', ...
    'Format', 'yyyyMMdd_HHmmss''Z'''));

Rf = 100e3;
Cpd = 5e-12;
A0 = 1e5;
ft_Hz = 100e6;
Cf_values = logspace(log10(0.2e-12), log10(47e-12), 48).';
f_Hz = logspace(0, 9, 2500).';

noiseParams = struct();
noiseParams.temperature_K = 300;
noiseParams.opamp_voltage_noise_V_per_sqrtHz = 3e-9;
noiseParams.opamp_current_noise_A_per_sqrtHz = 0.4e-12;
noiseParams.include_photodiode_shot_noise = true;
noiseParams.photodiode_dc_current_A = 1e-9;
noiseParams.reference_frequency_Hz = 1e3;

parameterRecord = string(sprintf( ...
    ['Rf=%.6g ohm; Cpd=%.6g F; A0=%.6g; ft=%.6g Hz; ' ...
     'Cf=logspace(log10(0.2e-12),log10(47e-12),48) F; ' ...
     'temperature=%.6g K; en=%.6g V/sqrtHz; in=%.6g A/sqrtHz; ' ...
     'photodiode_shot_enabled=%d; photodiode_dc_current=%.6g A; ' ...
     'frequency_grid=[%.6g, %.6g] Hz; ENBW_approx=(pi/2)*bandwidth'], ...
    Rf, Cpd, A0, ft_Hz, ...
    noiseParams.temperature_K, ...
    noiseParams.opamp_voltage_noise_V_per_sqrtHz, ...
    noiseParams.opamp_current_noise_A_per_sqrtHz, ...
    noiseParams.include_photodiode_shot_noise, ...
    noiseParams.photodiode_dc_current_A, min(f_Hz), max(f_Hz)));

rows = numel(Cf_values);
tradeoff = table( ...
    repmat("Cf_noise_bandwidth_sweep", rows, 1), ...
    repmat("tia_extension/scripts/run_08_noise_bandwidth_tradeoff.m", rows, 1), ...
    repmat(parameterRecord, rows, 1), ...
    repmat(Rf, rows, 1), ...
    Cf_values, ...
    repmat(Cpd, rows, 1), ...
    repmat(A0, rows, 1), ...
    repmat(ft_Hz, rows, 1), ...
    zeros(rows, 1), zeros(rows, 1), zeros(rows, 1), zeros(rows, 1), ...
    zeros(rows, 1), zeros(rows, 1), zeros(rows, 1), zeros(rows, 1), ...
    zeros(rows, 1), zeros(rows, 1), zeros(rows, 1), zeros(rows, 1), ...
    repmat(noiseParams.temperature_K, rows, 1), ...
    repmat(noiseParams.opamp_voltage_noise_V_per_sqrtHz, rows, 1), ...
    repmat(noiseParams.opamp_current_noise_A_per_sqrtHz, rows, 1), ...
    repmat(noiseParams.include_photodiode_shot_noise, rows, 1), ...
    repmat(noiseParams.photodiode_dc_current_A, rows, 1), ...
    repmat("first-pass MATLAB behavioural noise estimate; not measured or experimentally validated", rows, 1), ...
    'VariableNames', { ...
        'case_id', ...
        'source_script', ...
        'parameter_record', ...
        'Rf_ohm', ...
        'Cf_F', ...
        'Cpd_F', ...
        'A0', ...
        'ft_Hz', ...
        'fc_ideal_Hz', ...
        'capacitive_noise_gain', ...
        'gbw_margin_index', ...
        'bandwidth_Hz', ...
        'peaking_dB', ...
        'effective_noise_bandwidth_approx_Hz', ...
        'total_integrated_output_noise_V_rms', ...
        'feedback_resistor_integrated_output_noise_V_rms', ...
        'opamp_voltage_integrated_output_noise_V_rms', ...
        'opamp_current_integrated_output_noise_V_rms', ...
        'photodiode_shot_integrated_output_noise_V_rms', ...
        'input_referred_current_noise_density_at_reference_frequency_A_per_sqrtHz', ...
        'temperature_K', ...
        'opamp_voltage_noise_V_per_sqrtHz', ...
        'opamp_current_noise_A_per_sqrtHz', ...
        'photodiode_shot_noise_enabled', ...
        'photodiode_dc_current_A', ...
        'model_scope'});

for iCf = 1:numel(Cf_values)
    noise = tia_noise_first_pass( ...
        f_Hz, Rf, Cf_values(iCf), Cpd, A0, ft_Hz, noiseParams);

    tradeoff.fc_ideal_Hz(iCf) = noise.response.fc_ideal_Hz;
    tradeoff.capacitive_noise_gain(iCf) = ...
        noise.response.capacitive_noise_gain;
    tradeoff.gbw_margin_index(iCf) = noise.response.gbw_margin_index;
    tradeoff.bandwidth_Hz(iCf) = noise.metrics.bandwidth_Hz;
    tradeoff.peaking_dB(iCf) = noise.metrics.peaking_dB;
    tradeoff.effective_noise_bandwidth_approx_Hz(iCf) = ...
        noise.effective_noise_bandwidth_approx_Hz;
    tradeoff.total_integrated_output_noise_V_rms(iCf) = ...
        noise.total_integrated_output_noise_V_rms;
    tradeoff.feedback_resistor_integrated_output_noise_V_rms(iCf) = ...
        noise.component_integrated_output_noise_V_rms(1);
    tradeoff.opamp_voltage_integrated_output_noise_V_rms(iCf) = ...
        noise.component_integrated_output_noise_V_rms(2);
    tradeoff.opamp_current_integrated_output_noise_V_rms(iCf) = ...
        noise.component_integrated_output_noise_V_rms(3);
    tradeoff.photodiode_shot_integrated_output_noise_V_rms(iCf) = ...
        noise.component_integrated_output_noise_V_rms(4);
    tradeoff.input_referred_current_noise_density_at_reference_frequency_A_per_sqrtHz(iCf) = ...
        noise.input_referred_current_noise_density_reference_A_per_sqrtHz;
end

sourceCsv = fullfile(resultsDir, 'noise_tradeoff_summary.csv');
writetable(tradeoff, sourceCsv);

fig = figure('Color', 'w', 'Name', 'TIA noise bandwidth tradeoff');
tiledlayout(3, 1, 'Padding', 'compact', 'TileSpacing', 'compact');

nexttile;
loglog(tradeoff.Cf_F * 1e12, ...
    tradeoff.total_integrated_output_noise_V_rms * 1e6, ...
    'LineWidth', 1.5, 'Marker', 'o', 'MarkerSize', 4, ...
    'Color', [0.15 0.38 0.66]);
grid on;
box on;
ylabel('Output noise (uV rms)');
title('First-pass TIA noise-bandwidth trade-off');
styleAxes(gca);

nexttile;
loglog(tradeoff.Cf_F * 1e12, tradeoff.bandwidth_Hz, ...
    'LineWidth', 1.5, 'Marker', 'o', 'MarkerSize', 4, ...
    'Color', [0.68 0.28 0.18]);
grid on;
box on;
ylabel('-3 dB bandwidth (Hz)');
styleAxes(gca);

nexttile;
semilogx(tradeoff.Cf_F * 1e12, tradeoff.peaking_dB, ...
    'LineWidth', 1.5, 'Marker', 'o', 'MarkerSize', 4, ...
    'Color', [0.20 0.50 0.28]);
grid on;
box on;
xlabel('Feedback capacitance Cf (pF)');
ylabel('Peaking (dB)');
styleAxes(gca);

formats = exportFigureSet( ...
    fig, fullfile(figuresDir, 'tia_noise_bandwidth_tradeoff'));
close(fig);

keyParameters = sprintf( ...
    ['Rf=%.3g ohm; Cpd=%.3g F; A0=%.3g; ft=%.3g Hz; ' ...
     'Cf=0.2 pF to 47 pF; temperature=%.3g K; en=%.3g V/sqrtHz; ' ...
     'in=%.3g A/sqrtHz; photodiode shot enabled at Idc=%.3g A; ' ...
     'ENBW approx=(pi/2)*bandwidth'], ...
    Rf, Cpd, A0, ft_Hz, noiseParams.temperature_K, ...
    noiseParams.opamp_voltage_noise_V_per_sqrtHz, ...
    noiseParams.opamp_current_noise_A_per_sqrtHz, ...
    noiseParams.photodiode_dc_current_A);

appendFigureManifest( ...
    fullfile(figuresDir, 'figure_manifest_tia.csv'), ...
    "tia_noise_bandwidth_tradeoff.png", ...
    "tia_extension/scripts/run_08_noise_bandwidth_tradeoff.m", ...
    "tia_extension/results/noise_tradeoff_summary.csv", ...
    string(keyParameters), ...
    "First-pass MATLAB behavioural Cf sweep showing that larger feedback capacitance lowers bandwidth and peaking while generally reducing integrated output noise. This is not measured noise or experimental validation.", ...
    "first-pass MATLAB behavioural noise sweep", ...
    string(strjoin(formats, ';')), ...
    string(runId));

fprintf('Round 5 noise-bandwidth trade-off sweep complete.\n');
fprintf('Summary data: %s\n', sourceCsv);

function ensureDir(pathName)
if ~exist(pathName, 'dir')
    mkdir(pathName);
end
end

function styleAxes(ax)
set(ax, 'FontName', 'Arial', 'FontSize', 11, 'LineWidth', 1);
try
    disableDefaultInteractivity(ax);
catch
end
try
    axtoolbar(ax, {});
catch
end
end

function formats = exportFigureSet(figHandle, basePath)
formats = {};
try
    exportgraphics(figHandle, [basePath '.pdf'], 'ContentType', 'vector');
    formats{end+1} = 'pdf'; %#ok<AGROW>
catch
end
try
    exportgraphics(figHandle, [basePath '.svg'], 'ContentType', 'vector');
    formats{end+1} = 'svg'; %#ok<AGROW>
catch
end
try
    exportgraphics(figHandle, [basePath '.png'], 'Resolution', 600);
    formats{end+1} = 'png'; %#ok<AGROW>
catch
    print(figHandle, [basePath '.png'], '-dpng', '-r600');
    formats{end+1} = 'png'; %#ok<AGROW>
end
end

function appendFigureManifest(manifestPath, filename, script, sourceData, ...
        keyParameters, caption, dataType, exportFormats, runId)
header = "figure_filename,source_script,source_data,key_parameters," + ...
    "caption,data_type,export_formats,run_identifier";
ensureManifestHeader(manifestPath, header);
removeFigureEntry(manifestPath, filename);

fields = [filename, script, sourceData, keyParameters, caption, ...
    dataType, exportFormats, runId];
fid = fopen(manifestPath, 'a');
cleanup = onCleanup(@() fclose(fid));
fprintf(fid, '%s\n', csvJoin(fields));
end

function ensureManifestHeader(manifestPath, header)
if ~exist(manifestPath, 'file')
    fid = fopen(manifestPath, 'w');
    cleanup = onCleanup(@() fclose(fid));
    fprintf(fid, '%s\n', header);
    return;
end

text = fileread(manifestPath);
lines = regexp(text, '\r\n|\n|\r', 'split');
if ~isempty(lines) && strlength(string(lines{end})) == 0
    lines(end) = [];
end

if isempty(lines)
    lines = {char(header)};
elseif ~contains(string(lines{1}), "run_identifier")
    lines{1} = char(header);
    for iLine = 2:numel(lines)
        if strlength(string(lines{iLine})) > 0
            lines{iLine} = [lines{iLine} ',round2-baseline'];
        end
    end
end

fid = fopen(manifestPath, 'w');
cleanup = onCleanup(@() fclose(fid));
for iLine = 1:numel(lines)
    fprintf(fid, '%s\n', lines{iLine});
end
end

function removeFigureEntry(manifestPath, filename)
text = fileread(manifestPath);
lines = regexp(text, '\r\n|\n|\r', 'split');
keep = true(size(lines));
for iLine = 2:numel(lines)
    keep(iLine) = ~startsWith(string(lines{iLine}), filename + ",");
end
lines = lines(keep);

fid = fopen(manifestPath, 'w');
cleanup = onCleanup(@() fclose(fid));
for iLine = 1:numel(lines)
    if strlength(string(lines{iLine})) > 0
        fprintf(fid, '%s\n', lines{iLine});
    end
end
end

function row = csvJoin(fields)
parts = strings(1, numel(fields));
for iField = 1:numel(fields)
    parts(iField) = csvField(fields(iField));
end
row = char(strjoin(parts, ','));
end

function field = csvField(value)
field = string(value);
field = replace(field, """", """""");
if contains(field, ",") || contains(field, """") || ...
        contains(field, newline) || contains(field, sprintf('\r'))
    field = """" + field + """";
end
end
