function Gm = add_measurement_noise(G, magNoise_dB, phaseNoise_deg, seed)
% add_measurement_noise
% Adds virtual measurement-style magnitude and phase noise to a complex
% frequency response.
%
% Gm is generated by perturbing magnitude in dB and unwrapped phase in degrees.
%
% Inputs:
%   G              : clean complex frequency response
%   magNoise_dB    : standard deviation of magnitude noise in dB
%   phaseNoise_deg : standard deviation of phase noise in degrees
%   seed           : optional random seed
%
% Output:
%   Gm             : noisy complex frequency response

    if nargin < 4
        seed = [];
    end

    if ~isvector(G) || isempty(G)
        error('G must be a non-empty vector.');
    end

    G = G(:);

    if any(~isfinite(G))
        error('G must contain finite complex values.');
    end

    if ~isscalar(magNoise_dB) || ~isscalar(phaseNoise_deg) || ...
       ~isreal(magNoise_dB) || ~isreal(phaseNoise_deg) || ...
       ~isfinite(magNoise_dB) || ~isfinite(phaseNoise_deg)
        error('Noise standard deviations must be finite real scalar values.');
    end

    if magNoise_dB < 0 || phaseNoise_deg < 0
        error('Noise standard deviations must be non-negative.');
    end

    if ~isempty(seed)
        if ~isscalar(seed) || ~isreal(seed) || ~isfinite(seed) || seed < 0 || floor(seed) ~= seed
            error('seed must be empty or a non-negative integer scalar value.');
        end
        rng(seed);
    end

    mag = abs(G);

    if any(mag <= 0)
        error('Magnitude contains zero values, so dB conversion is invalid.');
    end

    mag_dB = 20*log10(mag);

    % Correct order: unwrap phase first, then add phase noise.
    phase_deg = unwrap(angle(G)) * 180/pi;

    mag_dB_noisy = mag_dB + magNoise_dB * randn(size(mag_dB));
    phase_deg_noisy = phase_deg + phaseNoise_deg * randn(size(phase_deg));

    Gm = 10.^(mag_dB_noisy/20) .* exp(1j * phase_deg_noisy*pi/180);
end
