function comparison = compare_tia_matlab_vs_spice(spice, matlabCase)
%COMPARE_TIA_MATLAB_VS_SPICE Compare MATLAB TIA model with SPICE AC data.
%
%   comparison = compare_tia_matlab_vs_spice(spice, matlabCase) computes a
%   clean model-level comparison between imported SPICE macromodel AC data
%   and the MATLAB behavioural TIA model for the same case parameters.
%
%   This function does not claim hardware validation.

arguments
    spice (1,1) struct
    matlabCase table
end

if height(matlabCase) ~= 1
    error('compare_tia_matlab_vs_spice:CaseSize', ...
        'matlabCase must contain exactly one row.');
end

Rf = matlabCase.Rf_ohm(1);
Cf = matlabCase.Cf_F(1);
Cpd = matlabCase.Cpd_F(1);
A0 = matlabCase.A0(1);
ft_Hz = matlabCase.ft_Hz(1);
Cin = getOptionalNumericColumn(matlabCase, 'Cin_F', 0);
Cstray = getOptionalNumericColumn(matlabCase, 'Cstray_F', 0);

response = tia_response( ...
    spice.f_Hz, Rf, Cf, Cpd, A0, ft_Hz, ...
    Cin=Cin, Cstray=Cstray);

matlabMetrics = extract_tia_metrics( ...
    response.f_Hz, response.Zt_nonideal, Rf, response.fc_ideal_Hz);
spiceMetrics = extract_tia_metrics( ...
    spice.f_Hz, spice.Zt, Rf, response.fc_ideal_Hz);

matlabMag_dBohm = 20*log10(abs(response.Zt_nonideal));
spiceMag_dBohm = 20*log10(abs(spice.Zt));

matlabPhase_deg = unwrap(angle(-response.Zt_nonideal)) * 180/pi;
spicePhase_deg = unwrap(angle(-spice.Zt)) * 180/pi;

magError_dB = spiceMag_dBohm - matlabMag_dBohm;
phaseError_deg = spicePhase_deg - matlabPhase_deg;

responseTable = table( ...
    spice.f_Hz, ...
    matlabMag_dBohm, spiceMag_dBohm, magError_dB, ...
    matlabPhase_deg, spicePhase_deg, phaseError_deg, ...
    'VariableNames', { ...
        'f_Hz', ...
        'matlab_mag_dBohm', 'spice_mag_dBohm', 'mag_error_dB', ...
        'matlab_phase_deg', 'spice_phase_deg', 'phase_error_deg'});

bandwidthErrorPct = 100 * ...
    (spiceMetrics.bandwidth_Hz - matlabMetrics.bandwidth_Hz) / ...
    matlabMetrics.bandwidth_Hz;

summaryTable = table( ...
    string(spice.source_file), ...
    getMetadataString(spice.metadata, 'case_label'), ...
    getMetadataString(spice.metadata, 'vendor_model'), ...
    Rf, Cf, Cpd, Cin, Cstray, A0, ft_Hz, ...
    matlabMetrics.bandwidth_Hz, spiceMetrics.bandwidth_Hz, ...
    bandwidthErrorPct, ...
    matlabMetrics.peaking_dB, spiceMetrics.peaking_dB, ...
    spiceMetrics.peaking_dB - matlabMetrics.peaking_dB, ...
    matlabMetrics.peaking_frequency_Hz, ...
    spiceMetrics.peaking_frequency_Hz, ...
    matlabMetrics.phase_at_bandwidth_deg, ...
    spiceMetrics.phase_at_bandwidth_deg, ...
    spiceMetrics.phase_at_bandwidth_deg - ...
        matlabMetrics.phase_at_bandwidth_deg, ...
    sqrt(mean(magError_dB.^2, 'omitnan')), ...
    sqrt(mean(phaseError_deg.^2, 'omitnan')), ...
    'VariableNames', { ...
        'spice_source_file', 'case_id', 'vendor_model', ...
        'Rf_ohm', 'Cf_F', 'Cpd_F', 'Cin_F', 'Cstray_F', 'A0', 'ft_Hz', ...
        'matlab_bandwidth_Hz', 'spice_bandwidth_Hz', ...
        'bandwidth_error_pct', ...
        'matlab_peaking_dB', 'spice_peaking_dB', ...
        'peaking_error_dB', ...
        'matlab_peak_frequency_Hz', 'spice_peak_frequency_Hz', ...
        'matlab_phase_at_bandwidth_deg', ...
        'spice_phase_at_bandwidth_deg', ...
        'phase_at_bandwidth_error_deg', ...
        'magnitude_rmse_dB', 'phase_rmse_deg'});

comparison = struct();
comparison.response_table = responseTable;
comparison.summary_table = summaryTable;
comparison.matlab_response = response;
comparison.matlab_metrics = matlabMetrics;
comparison.spice_metrics = spiceMetrics;
end

function value = getMetadataString(metadata, fieldName)
if isfield(metadata, fieldName)
    value = string(metadata.(fieldName));
else
    value = "";
end
end

function value = getOptionalNumericColumn(inputTable, columnName, defaultValue)
if any(strcmp(inputTable.Properties.VariableNames, columnName))
    value = inputTable.(columnName)(1);
    if isnan(value)
        value = defaultValue;
    end
else
    value = defaultValue;
end
end
