function summary = summarise_noise_contributions(noise, caseId)
%SUMMARISE_NOISE_CONTRIBUTIONS Build a result table for TIA noise terms.
%
%   summary = summarise_noise_contributions(noise, caseId) converts the
%   struct returned by tia_noise_first_pass into a CSV-ready table with one
%   row per major noise contribution plus one quadrature-total row.

arguments
    noise (1,1) struct
    caseId (1,1) string = "tia_noise_case"
end

componentNames = noise.component_names(:);
totalName = "total_quadrature";
allNames = [componentNames; totalName];
nRows = numel(allNames);

componentInputDensity = [ ...
    noise.feedback_current_noise_A_per_sqrtHz; ...
    noise.opamp_voltage_noise_V_per_sqrtHz; ...
    noise.opamp_current_noise_A_per_sqrtHz; ...
    noise.photodiode_shot_current_noise_A_per_sqrtHz; ...
    NaN];

componentInputUnits = [ ...
    "A/sqrt(Hz)"; ...
    "V/sqrt(Hz)"; ...
    "A/sqrt(Hz)"; ...
    "A/sqrt(Hz)"; ...
    "quadrature total"];

outputDensityReference = [ ...
    noise.component_output_noise_density_reference_V_per_sqrtHz(:); ...
    noise.output_noise_density_reference_V_per_sqrtHz];

integratedOutput = [ ...
    noise.component_integrated_output_noise_V_rms(:); ...
    noise.total_integrated_output_noise_V_rms];

inputReferredReference = [ ...
    noise.component_input_referred_current_noise_density_reference_A_per_sqrtHz(:); ...
    noise.input_referred_current_noise_density_reference_A_per_sqrtHz];

if noise.total_integrated_output_noise_V_rms > 0
    varianceFractionPct = 100 * integratedOutput.^2 ./ ...
        noise.total_integrated_output_noise_V_rms.^2;
else
    varianceFractionPct = zeros(nRows, 1);
end
varianceFractionPct(end) = 100;

parameterRecord = string(sprintf( ...
    ['Rf=%.6g ohm; Cf=%.6g F; Cpd=%.6g F; A0=%.6g; ft=%.6g Hz; ' ...
     'temperature=%.6g K; en=%.6g V/sqrtHz; in=%.6g A/sqrtHz; ' ...
     'photodiode_shot_enabled=%d; photodiode_dc_current=%.6g A; ' ...
     'frequency_grid=[%.6g, %.6g] Hz; ENBW_approx=(pi/2)*bandwidth'], ...
    noise.Rf, noise.Cf, noise.Cpd, noise.A0, noise.ft_Hz, ...
    noise.params.temperature_K, ...
    noise.params.opamp_voltage_noise_V_per_sqrtHz, ...
    noise.params.opamp_current_noise_A_per_sqrtHz, ...
    noise.params.include_photodiode_shot_noise, ...
    noise.params.photodiode_dc_current_A, ...
    min(noise.f_Hz), max(noise.f_Hz)));

summary = table( ...
    repmat(caseId, nRows, 1), ...
    allNames, ...
    repmat("tia_extension/scripts/run_07_noise_baseline.m", nRows, 1), ...
    repmat(parameterRecord, nRows, 1), ...
    repmat(noise.Rf, nRows, 1), ...
    repmat(noise.Cf, nRows, 1), ...
    repmat(noise.Cpd, nRows, 1), ...
    repmat(noise.A0, nRows, 1), ...
    repmat(noise.ft_Hz, nRows, 1), ...
    repmat(noise.params.temperature_K, nRows, 1), ...
    repmat(noise.params.include_photodiode_shot_noise, nRows, 1), ...
    repmat(noise.params.photodiode_dc_current_A, nRows, 1), ...
    componentInputDensity, ...
    componentInputUnits, ...
    repmat(noise.reference_frequency_Hz, nRows, 1), ...
    outputDensityReference, ...
    integratedOutput, ...
    varianceFractionPct, ...
    inputReferredReference, ...
    repmat(noise.metrics.bandwidth_Hz, nRows, 1), ...
    repmat(noise.metrics.peaking_dB, nRows, 1), ...
    repmat(noise.effective_noise_bandwidth_approx_Hz, nRows, 1), ...
    repmat(min(noise.f_Hz), nRows, 1), ...
    repmat(max(noise.f_Hz), nRows, 1), ...
    repmat(noise.model_scope, nRows, 1), ...
    'VariableNames', { ...
        'case_id', ...
        'component', ...
        'source_script', ...
        'parameter_record', ...
        'Rf_ohm', ...
        'Cf_F', ...
        'Cpd_F', ...
        'A0', ...
        'ft_Hz', ...
        'temperature_K', ...
        'photodiode_shot_noise_enabled', ...
        'photodiode_dc_current_A', ...
        'input_source_noise_density', ...
        'input_source_noise_density_unit', ...
        'reference_frequency_Hz', ...
        'output_noise_density_at_reference_frequency_V_per_sqrtHz', ...
        'integrated_output_noise_V_rms', ...
        'integrated_noise_variance_fraction_pct', ...
        'input_referred_current_noise_density_at_reference_frequency_A_per_sqrtHz', ...
        'bandwidth_Hz', ...
        'peaking_dB', ...
        'effective_noise_bandwidth_approx_Hz', ...
        'integration_f_min_Hz', ...
        'integration_f_max_Hz', ...
        'model_scope'});
end
